// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class AtmosphereRenderSkyRayMarchingKeys
    {
        public static readonly ValueParameterKey<float> Time = ParameterKeys.NewValue<float>(0.0f);
        public static readonly ValueParameterKey<float> CloudScale = ParameterKeys.NewValue<float>(0.0001f);
        public static readonly ValueParameterKey<float> CloudSpeed = ParameterKeys.NewValue<float>(0.1f);
        public static readonly ValueParameterKey<float> Cloudiness = ParameterKeys.NewValue<float>(0.8f);
        public static readonly ValueParameterKey<float> Exposure = ParameterKeys.NewValue<float>(2.0f);
    }
}
