// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class AtmosphereCloudsKeys
    {
        public static readonly ValueParameterKey<float> CloudHeight = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> CloudThickness = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> CloudOpacity = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector4> CloudSpeed = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector4> CloudScale = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<float> Time = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> TopSurfaceScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> BottomSurfaceScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> TurbulenceScale = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> CloudSoftness = ParameterKeys.NewValue<float>();
        public static readonly ObjectParameterKey<Texture> CloudHeightTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> GradientTexture = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> CloudSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
