// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class HistogramKeys
    {
        public static readonly ObjectParameterKey<Texture> ColorInput = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Buffer> HistogramBuffer = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> Exposure = ParameterKeys.NewObject<Buffer>();
    }
}
