// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class HistogramReduceKeys
    {
        public static readonly ObjectParameterKey<Buffer> Histogram = ParameterKeys.NewObject<Buffer>();
        public static readonly ObjectParameterKey<Buffer> Exposure = ParameterKeys.NewObject<Buffer>();
        public static readonly ValueParameterKey<float> TimeDelta = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<float> Tau = ParameterKeys.NewValue<float>(1.1f);
        public static readonly ValueParameterKey<uint> PixelCount = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<bool> AutoKey = ParameterKeys.NewValue<bool>(true);
        public static readonly ValueParameterKey<float> TargetLuminance = ParameterKeys.NewValue<float>(0.08f);
        public static readonly ValueParameterKey<float> MinExposure = ParameterKeys.NewValue<float>(1.0f / 64.0f);
        public static readonly ValueParameterKey<float> MaxExposure = ParameterKeys.NewValue<float>(64.0f);
    }
}
