// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace TR.Stride.Ocean
{
    public static partial class OceanGenerateMipsKeys
    {
        public static readonly ObjectParameterKey<SamplerState> BilinearClamp = ParameterKeys.NewObject<SamplerState>();
        public static readonly ObjectParameterKey<Texture> SrcMip = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutMip1 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutMip2 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutMip3 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> OutMip4 = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<uint> SrcMipLevel = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> NumMipLevels = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<Vector2> TexelSize = ParameterKeys.NewValue<Vector2>();
    }
}
