// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace TR.Stride.Ocean
{
    public static partial class OceanFastFourierTransformBaseKeys
    {
        public static readonly ObjectParameterKey<Texture> PrecomputedData = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Buffer0 = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<Texture> Buffer1 = ParameterKeys.NewObject<Texture>();
        public static readonly ValueParameterKey<bool> PingPong = ParameterKeys.NewValue<bool>();
        public static readonly ValueParameterKey<uint> Size = ParameterKeys.NewValue<uint>();
        public static readonly ValueParameterKey<uint> Step = ParameterKeys.NewValue<uint>();
    }
}
